### ISSUE TITLE
Version and Scope of Github Personal Access Token not Stated in README.md

### ISSUE THREAD

**Issue by GumbyXGames** [mattpannella/pocket-updater-utility#104]
The readme.md states you can add a Github Personal Access Token if you run up against a rate limit, but does not state which version of the token (Fine-grained or Classic token) nor the scope settings (if using Classic tokens).

I'm guessing you mean to use the fine-grained tokens but it would be helpful if it was mentioned in the readme

**Comment by mattpannella** [comment]
I'm using a classic token with mine
