### ISSUE TITLE
Improvement - SGB2 checksums

### ISSUE THREAD

**Issue by MAkeItLikeASir** [mattpannella/pocket-updater-utility#107]
Hi, I really like your software. I am using the SGB with the boot and bios rom from the SGB2. Works perfect. But when i update, your software makes a checksum for the bios and boot rom of the SGB core and it only checks for the SGB1 version. Then it overwrites the SGB2 files. It would be a nice improvement if it checks for both or is asking to use which one.  Thank you for creating this tool, makes it really easy to manage a pocket.

**Comment by mattpannella** [comment]
hey, i forgot to mention i added per-core settings for the automatic checksum/downloading of assets so now you can disable it just for the SGB core and it should solve your problem
just set coreSettings.Spiritualized.SuperGB.download_assets to false, in your settings json file

**Comment by MAkeItLikeASir** [comment]
Hi, i saw it in the updates. And yes it totally fixes it. Thank you for your time and hard work.
