### ISSUE TITLE
Instance json files include hidden files

### ISSUE THREAD

**Issue by Jeffersonian** [mattpannella/pocket-updater-utility#111]
Most of my bin/cue files in Assets/pce/common had corresponding hidden files (macOS).  When the instance JSON files were generated, these hidden files were included.  In many cases, the JSON file was not generated at all since the hidden files would create more than 27 tracks.

Suggestion: Files that begin with a . should be ignored when searching for bin/cue files when creating instance JSON files.

**Comment by mattpannella** [comment]
damn macos dotfiles strike again. thanks

**Comment by mattpannella** [comment]
should be fixed in 2.13.2
let me know how it goes

**Comment by mattpannella** [comment]
fixed in v2.13.2

**Comment by Jeffersonian** [comment]
Verified as fixed (tested 2.14.0), thanks so much!
