### ISSUE TITLE
Improvement - Updating PC Engine CD Core - BIOS and missing files

### ISSUE THREAD

**Issue by dritzthevampyr** [mattpannella/pocket-updater-utility#114]
As I was recreating JSON files for my games in Asset/pcecd/common, I checked the output from Terminal and noticed [BIOS] TurboGrafx CD Super System Card (USA) (v3.0).pce being added.  Is it possible to include [BIOS] Super CD-ROM System (Japan) (v3.0).pce?  This seems to be the most compatible BIOS for PC Engine CD and TurboGrafx CD games with this core.

> Checking Core: Mazamars312.PC Engine CD
> 0.1.5 is the most recent release, checking local core...
> local core found: 0.1.5
> Looking for Assets
> Already installed: [BIOS] TurboGrafx CD Super System Card (USA) (v3.0).pce
> Unable to find mpu.bin in archive
> Building instance json files.

Also, I realized when deleting old JSON files for my games that I accidentally deleted the mpu.bin and image_template.json under Mazamars312.PC Engine CD folder path.  From the above output, it says "unable to find mpu.bin", but doesn't repopulate the file if missing.  Can that also be included?

**Comment by mattpannella** [comment]
that bios file is based on what's in data.json, in the actual core package, so I don't actually have any control over that. it just checks for the required files and pulls them down in available
and similar for mpu.bin, that's actually part of the core. I believe it's related to a custom cpu the dev built. so easiest solution is delete the core and reinstall it. if you just delete the directory in Cores and run update again it will pull it down

**Comment by dritzthevampyr** [comment]
Thank you for the prompt response, @mattpannella.  I misunderstood as I thought you were pulling the BIOS file separately and not based upon the Core's data.json.  I also didn't see a mention of it on the Core's README.md aside from "_Make sure you have the HuCard bios..._".  

Got around to deleting the /Mazamars312.PC Engine CD directory under /Cores and under /Asset/pcecd and those files reappeared once /Mazamars312.PC Engine CD was added back to /Asset/pcecd.  Thanks!
