### ISSUE TITLE
JTCPS1 do not appear to install

### ISSUE THREAD

**Issue by Parodius79** [mattpannella/pocket-updater-utility#116]
Due to loss, I had to install new SD card for the Pocket. All cores reinstalled with the pocket updater, but JT CPS1 cores do not appear for installation. Have they been pulled?

**Comment by mattpannella** [comment]
CPS1 isn't public yet so the updater will not download/install it
if you are a patron and have beta access and manually install it, it should download most of the roms it supports, though
