### ISSUE TITLE
Choosing Download Required Assets in Menu does not check the Assets

### ISSUE THREAD

**Issue by luke86** [mattpannella/pocket-updater-utility#125]
pocket_updater_settings.json:
  "config": {
    "download_assets": false,
    "archive_name": "openFPGA-Files",
    "github_token": null,
    "download_firmware": false,
    "core_selector": false,
    "preserve_platforms_folder": false,
    "delete_skipped_cores": true,
    "download_new_cores": "yes",
    "build_instance_jsons": true,
    "crc_check": true
  },

I tried the new "6) Configuration Wizard" Feature, i said no to firmware and no to assets and just pressed return at the rest of the questions.

Now before i did this "0) Update All" always checked the Assets for new Files that are needed. But when i now choose "2) Download Required Assets" from the menu, i just get the following output and it ends after around 1 second. So it looks like nothing is checked.

output:
```
0) Update All
1) Update Firmware
2) Download Required Assets
3) Select Cores
4) Download Platform Image Packs
5) Generate Instance JSON Files
6) Configuration Wizard
7) Exit

Choose your destiny: 2
Checking for requied files...
agg23.Arduboy
-------------
agg23.Pong
-------------
agg23.NES
-------------
agg23.PC Engine
-------------
agg23.PokemonMini
-------------
agg23.SNES
-------------
agg23.WonderSwan
-------------
antongale.performan
-------------
antongale.slapfight
-------------
...
-------------
-------------
All Done
we did it, come again soon
```

**Comment by mattpannella** [comment]
try running it again. i think the bug has something to do with launching the app with download_assets set to true, running the wizard to make it false, and then running Download Assets. i just had it repro your bug there
but i quit and ran the app, went right to Download Assets and it worked
lemme know if that happens for you as well, i can push a fix later

**Comment by luke86** [comment]
Yes that worked!

"2) Download Required Assets" seems to ignore the skip option for the cores right now.

For example my config is set to the following:
"coreSettings": {
    "agg23.Arduboy": {
      "skip": true,
      "allowPrerelease": true
    },

output when i run 2:
```
Choose your destiny: 2
Checking for requied files...
agg23.Arduboy
Looking for Assets
Uh oh something went wrong.
Could not find a part of the path 'F:\Cores\agg23.Arduboy\core.json'.
```

**Comment by mattpannella** [comment]
great thats helpful, thanks

**Comment by mattpannella** [comment]
should be fixed in latest release. lemme know how it goes

**Comment by mattpannella** [comment]
ok 2.19.2 should address both issues

**Comment by luke86** [comment]
Works now! Thanks!
