### ISSUE TITLE
Display / read .txt files as "Rom notes"

### ISSUE THREAD

**Issue by DunhamGitHub** [mattpannella/pocket-updater-utility#133]
I think it would be great if the browser of cores could display .txt, .jpg (etc.) files.

Why: There are so many great patches around, improving sound, graphics, fixing common bugs, basic quality-of-life, etc. etc. ...when browsing Roms **on the APocket** it would be great to display / read them as _Quick-Info_

<img width="500" alt="Screenshot 2023-03-21 at 13 15 58" src="https://user-images.githubusercontent.com/6884752/226603198-4b721e23-54a1-4dbb-adcb-843bc0b5b47b.png">

<img width="500" alt="Screenshot 2023-03-21 at 13 36 14" src="https://user-images.githubusercontent.com/6884752/226607961-c39064fb-84c7-439f-a674-c7c1e6187cfc.png">

**Comment by mattpannella** [comment]
do you mean on the pocket itself?

**Comment by DunhamGitHub** [comment]
> do you mean on the pocket itself?

Yes I do...

Scenario:
-- I am browsing through all my roms
-- I want to quickly see what "Rom patch XY" means ...hence I can look at the adjacent .txt file / or screenshot

**Comment by mattpannella** [comment]
unfortunately, i have no control over any of that. the analogue firmware is closed source and only maintained by analogue. you'd have to make a feature request with them

**Comment by DunhamGitHub** [comment]
Thank you, I appreciate your reply
