### ISSUE TITLE
Maintain directory structure when generating instance .json files?

### ISSUE THREAD

**Issue by Loukey42** [mattpannella/pocket-updater-utility#143]
Would it be possible to add an option to maintain the same directory structure in the generated instance .json files as the rom/cd directories?

So for instance if you had the CD directories split by region (USA, JPN, EUR) could the json files also be sorted in the same fashion?

I know the pocket sync program already offers this, but I am a big fan of your more utilitarian tool.

**Comment by mattpannella** [comment]
you know, I actually planned on doing this and totally forgot lol

**Comment by mattpannella** [comment]
this is release in v2.24.0

**Comment by Loukey42** [comment]
Thank you so much!!! :)
