### ISSUE TITLE
"Firmware update found." False alarm

### ISSUE THREAD

**Issue by DunhamGitHub** [mattpannella/pocket-updater-utility#152]
Pocket Updater (2.26.3) opened after deleting settings.json file _(because cannot seem to have it download deleted Cores🫤)_ and it downloads a new **firmware** which is wrongfully flagged as new (see timestamp of the firmware.bin in the screenshot)

<img width="773" alt="Screenshot 2023-04-30 at 03 45 12" src="https://user-images.githubusercontent.com/6884752/235331608-ca60940e-6b7d-4a22-8166-0dc90a8abf3f.png">

**Comment by mattpannella** [comment]
that's because you deleted your settings file. it only knows what current firmware you have by checking the settings file and on a fresh install it always downloads the firmware as there's none in your settings yet

**Comment by DunhamGitHub** [comment]
Thank you for clearing that up
