### ISSUE TITLE
Have to press Enter for cores to be installed?

### ISSUE THREAD

**Issue by DunhamGitHub** [mattpannella/pocket-updater-utility#153]
Is it normal, that I have to press _ENTER_ + _no number input_ at following point to start the download process of Cores?!

* The given options are 0-7 yet only ENTER + _no number input_ does the trick)

<img width="489" alt="Screenshot 2023-04-30 at 03 51 03" src="https://user-images.githubusercontent.com/6884752/235331775-86ceffe1-466a-4290-982d-1716c2d20513.png">

**Comment by mattpannella** [comment]
hitting enter with no number just defaults to 0
you're saying if you enter 0 and then hit enter it doesnt work? what happens?

**Comment by DunhamGitHub** [comment]
So what happened was that when it downloads the "new" Firmware (no _settings file_) it then does not continue on to downloading Cores.

..works fine now that the _settings file_ has been created:
https://user-images.githubusercontent.com/6884752/235387634-710ad0f7-7a7e-4c53-bd49-6a1f97fdc85a.mov
