### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by rogalian** [mattpannella/pocket-updater-utility#154]
Not on a VPN or anything else unusual...
```
rogalian@water:~/Downloads$ ./pocket_updater_x64 -p /media/rogalian/APOCKET/
path: /media/rogalian/APOCKET/
Analogue Pocket Core Updater v2.26.3
Checking for updates...
Well, something went wrong. Sorry about that.
The SSL connection could not be established, see inner exception.

```

**Comment by mattpannella** [comment]
was it working previously or is this the first time you've run it

**Comment by rogalian** [comment]
Previous versions have worked. They now give 404 errors

Any way of getting more detail out?

**Comment by rogalian** [comment]
2.8.0 gives me a 404 error, I guess it's just plain too old now.

2.26.3 gives me the SSL error.

Just tried browsing the source code and opening any URLS I can find: this one in CoresService.cs 404s https://raw.githubusercontent.com/mattpannella/pocket-updater-utility/main/pocket_updater_cores.json

**Comment by rogalian** [comment]
I think I've found the problem, my ISP blocks https://archive.org/

Seeing if I can get this block removed.

**Comment by rogalian** [comment]
Yeah, that's fixed it.
