### ISSUE TITLE
Would you like to, by default, install new cores -> NO never works

### ISSUE THREAD

**Issue by amullr** [mattpannella/pocket-updater-utility#158]
using 2.28.1

when choosing option 3 to select core, I cannot get to choose NO :

Would you like to, by default, install new cores? [Y]es, [N]o, [A]sk for each: -> "N" or "n" always get the same as "A"

Please fix its so anoying there is TOO MUCH cores to choose one by one

Thanks

**Comment by mattpannella** [comment]
when you select no there, that means when new cores are released they are not automatically installed by the updater
if you run menu optjon 3 you have to choose your cores every time. what other option would you like?
you dont need to run that option all the time. select your cores once and never look at it again

**Comment by amullr** [comment]
If I choose No, I get to choose every core that's why I say it seems to be a bug

**Comment by amullr** [comment]
If I understand well in Program.cs line 179
                
case 3:
    List<Core> cores = await CoresService.GetCores();
    AskAboutNewCores(ref settings, true); <<-- ask me "Yes", "No", "A"
    RunCoreSelector(ref settings, cores); <<-- there is a if-else logic that only handle two options; "yes" otherwise "No" and "A" the same way

**Comment by mattpannella** [comment]
it's supposed to show every core. that menu option is for listing every core and letting you choose the ones you want
the question about new cores in the beginning is for when you launch the app, if new cores were released since you last chose your cores it will either auto choose, ignore, or ask you about them at launch

**Comment by amullr** [comment]
Ok
