### ISSUE TITLE
basic linux question

### ISSUE THREAD

**Issue by theVanZan** [mattpannella/pocket-updater-utility#166]
I'm on MX Linux. I can't seem to run the updater off the SD card. It think it's because it's a removable device and it may not be mounted correctly with exec permissions. But I can't seem to figure it out.

**Comment by mattpannella** [comment]
what happens when you try?

**Comment by theVanZan** [comment]
I can't make the pocket_updater_x64 binary executable so "sudo ./pocket_updater_x64" gives a "command not found" error.

The fact the Micro SD is FAT32 might also be a problem.

**Comment by mattpannella** [comment]
try to chown +x the file to make sure it's executable

**Comment by theVanZan** [comment]
Do you mean chmod +x? Sadly I tried that and it had no effect.

**Comment by mattpannella** [comment]
woops yeah sorry haha.
I guess it's possible the build is bad? I can try testing later

**Comment by KevinGaudry** [comment]
any update on the issue ? can't run it either, on ubuntu 22.04

**Comment by mattpannella** [comment]
is your sd card mounted with the noexec flag set? i think ubuntu may do that by default

you could also try moving the binary to your local drive and running it with the -p parameter and pass in the path to your sd card
```
./pocket_updater -p /mnt/to/sdcard
```

**Comment by mattpannella** [comment]
sorry i dont have a linux machine to test this on much. i've run it in WSL in windows a few times to verify it works, but i mostly rely on github issues reported from other people to find bugs in the linux build

**Comment by mattpannella** [comment]
did you get a chance to try this?

**Comment by theVanZan** [comment]
I didn't. I have too many handhelds/devices. I'll try it out later today and report back.

**Comment by theVanZan** [comment]
> ./pocket_updater -p /mnt/to/sdcard

Just tried it and it works a treat! Thank you.

**Comment by TomFaulkner** [comment]
Perhaps this should be included in the documentation? On a FAT32 filesystem chmod isn't going to do anything. Mounting executable leads to an error writing a json file on start.

I think the `-p` option should probably be the recommended method.
