### ISSUE TITLE
Taito SJ Core Roms?

### ISSUE THREAD

**Issue by gregmariotti** [mattpannella/pocket-updater-utility#167]
this is the error message I'm getting...thanks!

<img width="568" alt="Screenshot 2023-07-07 at 6 51 49 AM" src="https://github.com/mattpannella/pocket-updater-utility/assets/115591167/5759f7f3-205f-4020-b3cd-06cdfa4db56f">

**Comment by mattpannella** [comment]
hm. did you update any of the core files by hand?

**Comment by krali27** [comment]
I'm seeing this in Windows 11, running as admin, works for all other cores-- could it be related? did not manually install/update anything.

antongale.taitosj
Looking for Assets
Unable to find alpine.rom in archive
Unable to find hwrace.rom in archive
Unable to find waterski.rom in archive
Unable to find bioatack.rom in archive
Unable to find junglek.rom in archive
Unable to find spacecr.rom in archive
Unable to find elevaorb.rom in archive
Unable to find piratpet.rom in archive
Unable to find timetunl.rom in archive
Unable to find wwestern.rom in archive
Unable to find spaceskr.rom in archive
....
All Done
Assets Not Found:
Assets\taitosj\common\alpine.rom
Assets\taitosj\common\hwrace.rom
Assets\taitosj\common\waterski.rom
Assets\taitosj\common\bioatack.rom
Assets\taitosj\common\junglek.rom
Assets\taitosj\common\spacecr.rom
Assets\taitosj\common\elevaorb.rom
Assets\taitosj\common\piratpet.rom
Assets\taitosj\common\timetunl.rom
Assets\taitosj\common\wwestern.rom
Assets\taitosj\common\spaceskr.rom
Assets\pcecd\common\bios_1_0_usa.pce

we did it, come again soon

**Comment by gregmariotti** [comment]
files are now downloadable..not sure what you did...but THANK YOU!!
