### ISSUE TITLE
"Index was out of range" in menu

### ISSUE THREAD

**Issue by p-rintz** [mattpannella/pocket-updater-utility#177]
Starting pocket-updater-utility fresh without any settings (or with defaults, on second start+) will run into the following error on the menu.

When simply starting it with:
pocket-updater-utility -p test/

`Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')`

Forcing an update works fine and it downloads everything. The menu just doesn't work.

OS: NixOS Linux
Version: 2.32.1

Do you need any other information?

**Comment by mattpannella** [comment]
hm. i just tested on macos by deleting my settings file and running if from the cli with the -p param and i'm not getting the error
i can try in linux a bit later. maybe its something specific (i generally only really test on my macbook)

**Comment by mattpannella** [comment]
can you post your settings file?

**Comment by mattpannella** [comment]
wait, woops. i know whats wrong. sorry about that

**Comment by p-rintz** [comment]
```
{
  "firmware": {
    "version": ""
  },
  "config": {
    "download_assets": true,
    "archive_name": "openFPGA-Files",
    "github_token": null,
    "download_firmware": true,
    "core_selector": true,
    "preserve_platforms_folder": false,
    "delete_skipped_cores": true,
    "download_new_cores": null,
    "build_instance_jsons": true,
    "crc_check": true,
    "fix_jt_names": true,
    "skip_alternative_assets": true,
    "use_custom_archive": false,
    "custom_archive": {
      "url": "https://updater.retrodriven.com",
      "index": "updater.php"
    }
  },
  "coreSettings": {}
}
```

Havent changed anything though, as I just compiled the new version and tried to test if everything is working.

**Comment by p-rintz** [comment]
> wait, woops. i know whats wrong. sorry about that

Ah, thats good.

**Comment by fooness** [comment]
> hm. i just tested on macos by deleting my settings file and running if from the cli with the -p param and i'm not getting the error i can try in linux a bit later. maybe its something specific (i generally only really test on my macbook)

I’m experiencing the same error when executing `./pocket_updater` with or without existing `pocket_updater_settings.json` file **on my SD card**; there’s no error when running `./pocket_updater` *on my MacBook’s SSD*.

Maybe only coincidence, as that difference sounds ridiculous …

**Comment by mattpannella** [comment]
sorry guys ill fix it in a few here. i did the last patch in a hurry cuz i'm working, but i made a stupid mistake cuz i did it quickly lol

**Comment by mattpannella** [comment]
should be fixed in 2.32.2

**Comment by mattpannella** [comment]
i'll leave this open til you guys confirm the issue's resolved

**Comment by fooness** [comment]
> i'll leave this open til you guys confirm the issue's resolved

*Works on my machine.*

Can confirm that this issue is resolved for me.

Thank you very much for all your efforts.

**Comment by p-rintz** [comment]
Yep. Works. Thank you.
