### ISSUE TITLE
How get Arcade, Computer, Console folders? 

### ISSUE THREAD

**Issue by Mika73** [mattpannella/pocket-updater-utility#181]
Hi

I been using Pocket updater with Mac and all my FPGA systems are at same list. It just shows all. I am missing those Arcade, Computer, Console etc folders. I been watching Analogue videos at YouTube and others have those. I wonder how I would get those sub folders for different systems?

**Comment by mattpannella** [comment]
Settings > Analogue OS > Group openFPGA
