### ISSUE TITLE
Well, something went wrong. Sorry about that.

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [mattpannella/pocket-updater-utility#183]
Any ideas what I might need to do to sort this error?

Pocket % ./pocket_updater -p /Volumes/Pocket 
Pocket Updater Utility v2.34.0
Checking for updates...
Well, something went wrong. Sorry about that.
The JSON value could not be converted to System.String. Path: $.config.download_new_cores | LineNumber: 12 | BytePositionInLine: 30.

Worked fine first time, but second run fails?

**Comment by mattpannella** [comment]
can you post the contents of your settings json file?

**Comment by ChocoChopin** [comment]
Lol, the first thing the executable did when I selected the "update all" option was uninstall all of my cores for no apparent reason and then error out. This was after extracting the file and running the executable, zero settings changes. Why on earth would the update function even call anything that *removes* stuff? 

Starting update process...
Checking for firmware updates...
Firmware up to date.
-------------
Uninstalling N:\Cores\agg23.GameAndWatch
-------------
Uninstalling N:\Cores\agg23.NES
-------------
Uninstalling N:\Cores\agg23.PC Engine
-------------
Uninstalling N:\Cores\agg23.SNES
-------------
Uninstalling N:\Cores\agg23.Tamagotchi_P1
-------------
Uninstalling N:\Cores\ericlewis.Asteroids
-------------
Uninstalling N:\Cores\ericlewis.DonkeyKong
-------------
Uninstalling N:\Cores\jotego.jtoutrun
-------------
Uninstalling N:\Presets\jotego.jtoutrun
-------------
Uninstalling N:\Cores\Mazamars312.PC Engine CD
-------------
Uninstalling N:\Cores\boogermann.digdug
-------------
Uninstalling N:\Cores\boogermann.galaga
-------------
Uninstalling N:\Cores\ericlewis.Genesis
-------------
Uninstalling N:\Cores\pram0d.garegga
-------------
Uninstalling N:\Cores\pram0d.kingdmgp
-------------
Uninstalling N:\Cores\pram0d.sstriker
-------------
Uninstalling N:\Cores\somhi.flappybird
-------------
Uninstalling N:\Cores\Spiritualized.GB
-------------
Uninstalling N:\Cores\Spiritualized.GBA
-------------
Uninstalling N:\Cores\Spiritualized.GBC
-------------
Uninstalling N:\Cores\Spiritualized.NES
-------------
Uninstalling N:\Cores\Spiritualized.SuperGB
-------------
-------------
Update Process Complete
Well, something went wrong. Sorry about that.
Object reference not set to an instance of an object.

**Comment by mattpannella** [comment]
did you unselect every core? it uninstalls the ones you don't want to update, by default. there's a setting to keep stuff installed even if you don't want to update it

the error at the end is a bug I need to fix, unrelated

**Comment by ChocoChopin** [comment]
I just don't understand why you would make that the default behavior without warning the end user. I opted not to update cores because I just wanted my cores to be left alone for the time being, there was no possible way I could have predicted that would end in all of my hand-fiddled-with configs being deleted. Why would the option to _not_ suddenly delete stuff unprompted be the one you have to opt into, rather than the other way around?

**Comment by mattpannella** [comment]
you didn't lose anything just select the cores you want and hit update again. it'll reinstall them all in a few minutes

**Comment by ChocoChopin** [comment]
Unfortunately that's not going to restore the .json config files for those cores that I modified myself--for example, I wanted an NES core that could output 8:7. That requires manually editing the video.json file for that core. Oh well, I'll just have to retrace my steps.

**Comment by mattpannella** [comment]
ah yeah. well disable the setting that removes cores you aren't tracking. it's on by default because everyone kept asking for it when I first started working on this

**Comment by mattpannella** [comment]
if you read the readme it says all the default settings

**Comment by ChocoChopin** [comment]
While I have you attention: I'm using pocket-updater to generate the necessary JSON files for PCE-CD via option 5. I've got both a .chd version and bin/cue/wav version of Chi no Rondo in the pcecd/common directory, which I'm pretty sure is where they're supposed to be, but I'm not getting any JSON generated in the Mazamars312.PC Engine CD. I'm kind of at a loss, since the app just reports that it's finished building the files.
