### ISSUE TITLE
 pocket_updater_x64 downloads assets to the binary's directory instead of the execution directory.

### ISSUE THREAD

**Issue by kresp0** [mattpannella/pocket-updater-utility#187]
**Description**
When I execute pocket_updater_x64 v2.35.0 from /media/kresp0/POCKET, with the binary located in /home/kresp0/bin/ (which is in my $PATH), the assets get downloaded to /home/kresp0/bin/ instead of /media/kresp0/POCKET.

I can't just copy the binary to the SD and run it from there, as it is FAT32 and won't accept execution permissions on Linux.

**To Reproduce**
- Place pocket_updater_x64 in /home/myuser/bin/ (which is in $PATH).
- Navigate to /media/s/POCKET in the terminal.
- Execute pocket_updater_x64.
- Observe that assets are downloaded to /home/myuser/bin/ instead of /media/s/POCKET.

**Expected behavior**
When invoking pocket_updater_x64 from any directory, I expect it to download the assets or any other files to the current directory (i.e., the directory from which the command was invoked).

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Debian 12

Thanks!

**Comment by mattpannella** [comment]
if you pass -p you can give it the path to the sdcard. otherwise right now it just uses the directory of the executable

**Comment by kresp0** [comment]
Right, I missed that option 🙈

Thank you!

**Comment by mattpannella** [comment]
no worries. it should work the way you're describing. I just haven't gotten to it haha
