### ISSUE TITLE
Include the cores from terminator2k2 separately

### ISSUE THREAD

**Issue by tarikalmashni** [mattpannella/pocket-updater-utility#193]
Since it's rather unlikely that the changes that terminator2k2 did will be streamlined into the cores he forked it from I would love for terminator2k2's forked cores of SNES and Neo Geo to be included separately (with their own core info json) into the updater.
I already did this with his SNES core fork of agg23 in the past but since he now also released a Neo Geo fork, I thought this would make sense for the auto-updaters.

His GitHub is here: https://github.com/terminator2k2 (@terminator2k2)

A little bit of context:
YouTube Pixel Cherry Ninja brought to my attention that terminator2k2 forked Adam's SNES core and applied some fixes on top of it, especially for certain rom hacks to be playable on the Analogue Pocket. Since by default those are to be copied and overwritten over the core from Adam, those fixes would basically be reverted with each new update from Adam (and it's likely that Adam won't include them). Therefore it should be kept as a separate core imho. Same applies to his newly released Neo Geo core fork which enables three additional games to be compatible.

**Comment by mattpannella** [comment]
if he wants them included, cores can be submitted to the inventory here: https://github.com/openfpga-cores-inventory/analogue-pocket/issues/new/choose

this is what the updaters pull their lists from

**Comment by mattpannella** [comment]
but in order for these to work he needs to actually build his own releases
they can't be "agg23.SNES" etc anymore

**Comment by mattpannella** [comment]
probably should be brought up in issues on t2k2's repos, if you want to get his stuff on there

**Comment by terminator2k2** [comment]
im hoping these commits make there way into the official repo's soon, so ill leave as is for now
