### ISSUE TITLE
PCECD Json creator

### ISSUE THREAD

**Issue by undeadindustries** [mattpannella/pocket-updater-utility#196]
I can't seem to get the PCECD JSON creator to work. Is there a list of exact game name that you use?
Here is the error:
Choose your destiny:
  [0] Update All
  [1] Update Firmware
  [2] Download Required Assets
  [3] Select Cores
  [4] Download Platform Image Packs
=>[5] Generate Instance JSON Files
  [6] Generate Game and Watch ROMS
  [7] Settings
  [8] Exit

Do you want to overwrite existing json files? [y/N] 
yMazamars312.PC Engine CD
Building instance json files.
Well, something went wrong. Sorry about that.
Input/output error : '/Volumes/pocket/Assets/pcecd/common/Beyond Shadowgate'

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**To Reproduce**
run the updater
select option 5
select y

**Expected behavior**
JSON file created

**Desktop (please complete the following information):**
MacOS Sonoma 14.1.1 apple silicon.

**Contents of settings file**
please attach the contents of pocket_updater_settings.json
{
  "firmware": {
    "version": ""
  },
  "config": {
    "download_assets": true,
    "archive_name": "openFPGA-Files",
    "github_token": null,
    "download_firmware": true,
    "core_selector": true,
    "preserve_platforms_folder": false,
    "delete_skipped_cores": true,
    "download_new_cores": "yes",
    "build_instance_jsons": true,
    "crc_check": true,
    "fix_jt_names": true,
    "skip_alternative_assets": true,
    "use_custom_archive": false,
    "custom_archive": {
      "url": "https://updater.retrodriven.com",
      "index": "updater.php"
    }
  },
  "coreSettings": {
    "agg23.Arduboy": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.GameAndWatch": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.NES": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.PC Engine": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.PokemonMini": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.Pong": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.SNES": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.Tamagotchi_P1": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.WonderSwan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.exerion": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.performan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.slapfight": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.taitosj": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.Asteroids": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.Dominos": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.DonkeyKong": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.LunarLander": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.QBert": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.RadarScope": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.SpaceRace": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.SuperBreakout": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtaliens": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtbtiger": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtbubl": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcastle": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcomsc": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcontra": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcop": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcps1": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcps15": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcps2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtdd": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtdd2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtexed": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtfround": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtgng": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtgunsmk": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkarnov": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkicker": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkiwi": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkunio": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtmikie": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtninja": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtoutrun": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtpang": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtpinpon": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtrastan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtroadf": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtroc": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jts16": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jts16b": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsarms": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsbaskt": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsectnz": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsf": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtshanon": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtshouse": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsimson": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttmnt": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttora": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttrack": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttrojan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtvigil": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtyiear": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.Amiga": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.NeoGeo": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.NeoGeo_Overdrive": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.PC Engine CD": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "nullobject.tecmo": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.bankpanic": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.congo": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.digdug": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.galaga": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.gberet": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.pooyan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.supervision": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.xevious": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.Genesis": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.bakraid": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.batrider": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.garegga": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.kingdmgp": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.snowbros2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.sstriker": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "RndMnkIII.alphamission": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "somhi.flappybird": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spacemen3.PDP1": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.2600": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.7800": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Adventurevision": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Arcadia": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.ChannelF": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Coleco": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Creativision": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GB": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GBA": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GBC": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GG": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Gamate": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Gameking": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Genesis": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Intv": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Megaduck": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.NES": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Odyssey2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.SG-1000": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.SMS": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Studio2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.SuperGB": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Supervision": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.VideoBrain": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    }
  }
}

**Comment by mattpannella** [comment]
sorry i somehow missed this
is `/Volumes/pocket/Assets/pcecd/common/Beyond Shadowgate` the full path to the game, or is it truncated?
what do the files inside that folder look like?

**Comment by undeadindustries** [comment]
Doh. I was able to fix this. It's working perfect. That folder was empty. Must have been an issue with binmerge. But working great now.
