### ISSUE TITLE
"Enable All Display Modes" Warning Message...

### ISSUE THREAD

**Issue by DunhamGitHub** [mattpannella/pocket-updater-utility#210]
*** Cores and Display Modes work regardless ***

- Put Firmware 2.0 on SD
- Put Pocket Updater 2.41.0 (Mac) on SD
- Ran Pocket Updater
- Pressed Select Cores (GB, GBC, GBC, SNES only...)
- Pressed "Update All"
- Pressed "Enable All Display Modes"

Warning / Error: "Object reference not set..." (see screenshot)

<img width="331" alt="Screenshot 2023-12-25 at 08 55 44" src="https://github.com/mattpannella/pocket-updater-utility/assets/6884752/703b4dab-e52b-41d8-a3b0-4610e60b82a8">

**Comment by intrepidsilence** [comment]
I have this issue as well.

**Comment by mattpannella** [comment]
you can ignore the error, it's unrelated.

**Comment by JonAbrams** [comment]
I get this error too on my Mac (M1 Pro, MacOS 14.2.1). For me though, it updates two random cores (jotego.jttwin16, jotego.jtvulgus), then says All Done. Remaining cores appear untouched. Same results when running it again. I tried deleting `pocket_updater_settings.json`, but no luck.

**Comment by mattpannella** [comment]
it only runs against the cores you have selected. 

the error at the end is unrelated

**Comment by mattpannella** [comment]
fixed in 2.42.0
