### ISSUE TITLE
Enable All Display Modes is broken.

### ISSUE THREAD

**Issue by IdiotBlueMage** [mattpannella/pocket-updater-utility#221]
When hitting the 7 key, every single core brings up the same error:

> Uh oh something went wrong.
The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

 - OS: Linux
 - Version: Latest
[pocket_updater_settings.json](https://github.com/mattpannella/pocket-updater-utility/files/13875999/pocket_updater_settings.json)

**Comment by mattpannella** [comment]
if the files are empty then it's not going to work. I don't necessarily know what cleared them but you need to restore the files or nothing is gonna work

**Comment by IdiotBlueMage** [comment]
I deleted and reinstalled all of my cores, that seemed to fix the problem.  Still no clue what happened to the json files but everything works as expected now.
