### ISSUE TITLE
[Feature Request] Skip update-self

### ISSUE THREAD

**Issue by emillassen** [mattpannella/pocket-updater-utility#222]
**Describe the feature**
The addition of a CLI command or setting to skip the update-self feature.

**Expected behavior**
The update-self feature would be skipped, and the utility would proceed as normal.

**Reason**
The utility runs the update-self feature on launch and then fails, as the NixOS file system is read-only. This would alleviate the problem.

**Desktop**
 - OS: [NixOS]
 - Version [23.11]

PS. Thank you for a great piece of software.

**Comment by mattpannella** [comment]
going to add a --skip-update option to the next release
it actually only checks for updates if you run the app without any options, or menu. but with menu you'll be able to skip update too

**Comment by mattpannella** [comment]
3.0.0 is live, should be good to go with the new param
