### ISSUE TITLE
"Error in framework RS: bridge not responding" issue

### ISSUE THREAD

**Issue by kylereardon** [mattpannella/pocket-updater-utility#43]
Here's everything in the terminal after I run it:

Analogue Pocket Core Updater v2.5.0
Checking for updates...
Starting update process...
Checking for firmware updates...
Firmware up to date.
-------------
Checking Core: agg23.Arduboy
0.9.0 is the most recent release, checking local core...
local core found: v0.9.0
Up to date. Skipping core
-------------
Checking Core: agg23.Pong
1.2.0 is the most recent release, checking local core...
local core found: v1.2.0
Up to date. Skipping core
-------------
Checking Core: agg23.NES
0.2.0 is the most recent release, checking local core...
local core found: v0.2.0
Up to date. Skipping core
-------------
Checking Core: agg23.SNES
0.3.2 is the most recent release, checking local core...
local core found: v0.3.2
Up to date. Skipping core
-------------
Checking Core: ericlewis.Asteroids
1.0.1 is the most recent release, checking local core...
local core found: v1.0.1
Looking for Assets
Asset already installed: asteroid.rom
Up to date. Skipping core
-------------
Checking Core: ericlewis.Dominos
0.0.1 is the most recent release, checking local core...
local core found: v0.0.1
Looking for Assets
Asset already installed: dominos.rom
Up to date. Skipping core
-------------
Checking Core: ericlewis.DonkeyKong
0.0.1 is the most recent release, checking local core...
local core found: v0.0.1
Looking for Assets
Asset already installed: dkong.rom
Up to date. Skipping core
-------------
Checking Core: ericlewis.Genesis
0.4.2 is the most recent release, checking local core...
local core found: v0.4.2
Up to date. Skipping core
-------------
Checking Core: ericlewis.LunarLander
0.9.1 is the most recent release, checking local core...
local core found: v0.9.1
Looking for Assets
Asset already installed: llander.rom
Up to date. Skipping core
-------------
Checking Core: ericlewis.SpaceRace
1.0.1 is the most recent release, checking local core...
local core found: v1.0.1
Up to date. Skipping core
-------------
Checking Core: ericlewis.SuperBreakout
0.0.1 is the most recent release, checking local core...
local core found: v0.0.1
Looking for Assets
Asset already installed: sbrkout.rom
Up to date. Skipping core
-------------
Checking Core: ericlewis.QBert
1.1.0 is the most recent release, checking local core...
local core found: v1.1.0
Looking for Assets
Asset already installed: qbert.rom
Up to date. Skipping core
-------------
Checking Core: Mazamars312.NeoGeo
Alpha_0.7.5_2022-19-09 is the most recent release, checking local core...
local core found: v0.7.5
Looking for Assets
Asset already installed: uni-bios_1_0.rom
Asset already installed: 000-lo.lo
Asset already installed: sfix.sfix
Up to date. Skipping core
-------------
Checking Core: nullobject.tecmo
v2.0 is the most recent release, checking local core...
local core found: v2.0.0
Looking for Assets
Asset already installed: gemini.rom
Asset already installed: rygar.rom
Asset already installed: geminij.rom
Asset already installed: rygar2.rom
Asset already installed: rygarj.rom
Asset already installed: silkworm.rom
Asset already installed: silkwrmj.rom
Up to date. Skipping core
-------------
Checking Core: boogermann.bankpanic
0.1.0 is the most recent release, checking local core...
local core found: v0.1.0
Looking for Assets
Asset already installed: bankp.rom
Asset already installed: combh.rom
Up to date. Skipping core
-------------
Checking Core: boogermann.digdug
0.1.0 is the most recent release, checking local core...
local core found: v0.1.0
Looking for Assets
Asset already installed: digdug.rom
Asset already installed: digduat1.rom
Asset already installed: digdug1.rom
Asset already installed: digdugat.rom
Asset already installed: digsid.rom
Up to date. Skipping core
-------------
Checking Core: boogermann.galaga
v0.1.0 is the most recent release, checking local core...
local core found: v0.1.0
Looking for Assets
Asset already installed: galaga.rom
Asset already installed: galagads.rom
Asset already installed: galagaef.rom
Asset already installed: galagamf.rom
Asset already installed: galagamw.rom
Asset already installed: galagao.rom
Asset already installed: galagosb.rom
Asset already installed: galagost.rom
Asset already installed: galaped.rom
Asset already installed: galgaxin.rom
Asset already installed: gatsbee.rom
Asset already installed: nebulbee.rom
Asset already installed: vgalaga.rom
Asset already installed: vgalagaf.rom
Asset already installed: vgalagam.rom
Up to date. Skipping core
-------------
Checking Core: boogermann.gberet
0.1.1 is the most recent release, checking local core...
local core found: v0.1.1
Looking for Assets
Asset already installed: gberet.rom
Asset already installed: mrgoemon.rom
Asset already installed: rushatck.rom
Up to date. Skipping core
-------------
Checking Core: boogermann.pooyan
0.1.0 is the most recent release, checking local core...
local core found: v0.1.0
Looking for Assets
Asset already installed: pooyan.rom
Asset already installed: pooyaiag.rom
Asset already installed: pooyans.rom
Asset already installed: pootan.rom
Up to date. Skipping core
-------------
Checking Core: boogermann.supervision
0.1.1 is the most recent release, checking local core...
local core found: v0.1.1
Up to date. Skipping core
-------------
Checking Core: boogermann.xevious
0.1.0 is the most recent release, checking local core...
local core found: v0.1.0
Looking for Assets
Asset already installed: battles2.rom
Asset already installed: gaous.rom
Asset already installed: sxevious.rom
Asset already installed: xeviblk.rom
Asset already installed: xevios.rom
Asset already installed: xevious.rom
Asset already installed: xevious3.rom
Asset already installed: xevious4.rom
Asset already installed: xevious5.rom
Asset already installed: xevioush.rom
Up to date. Skipping core
-------------
Checking Core: Spacemen3.PDP1
v1.1.0 is the most recent release, checking local core...
local core found: v3.1.0
Up to date. Skipping core
-------------
Checking Core: Spiritualized.GB
v1.3.0 is the most recent release, checking local core...
local core found: v1.3.0
Up to date. Skipping core
-------------
Checking Core: Spiritualized.GBA
v1.2.0 is the most recent release, checking local core...
local core found: v1.2.0
Looking for Assets
Asset already installed: gba_bios.bin
Up to date. Skipping core
-------------
Checking Core: Spiritualized.GBC
v1.3.0 is the most recent release, checking local core...
local core found: v1.3.0
Looking for Assets
Asset already installed: gbc_bios.bin
Asset already installed: dmg_bios.bin
Up to date. Skipping core
-------------
Checking Core: Spiritualized.NES
1.0.0 is the most recent release, checking local core...
local core found: v1.0.0
Looking for Assets
Asset already installed: fds.bios
Up to date. Skipping core
-------------
Checking Core: Spiritualized.GG
v1.3.0 is the most recent release, checking local core...
local core found: v1.3.0
Up to date. Skipping core
-------------
Checking Core: Spiritualized.SMS
v1.2.0 is the most recent release, checking local core...
local core found: v1.2.0
Up to date. Skipping core
-------------
Checking Core: Spiritualized.SG-1000
v1.2.0 is the most recent release, checking local core...
local core found: v1.2.0
Up to date. Skipping core
-------------
-------------
Update Process Complete
we did it, come again soon

**Comment by kylereardon** [comment]
I formatted my card to do it again from scratch, thought you might want that info as well. Here's what's in the terminal on a first load:
Analogue Pocket Core Updater v2.5.0
Checking for updates...
Select your cores! The available cores will be listed 1 at a time. For each one, hit 'n' if you don't want it installed, or just hit enter if you want it. Ok you've got this. Here we go...
agg23.Arduboy?[y/n]
agg23.Pong?[y/n]
agg23.NES?[y/n]
agg23.SNES?[y/n]
ericlewis.Asteroids?[y/n]
ericlewis.Dominos?[y/n]
ericlewis.DonkeyKong?[y/n]
ericlewis.Genesis?[y/n]
ericlewis.LunarLander?[y/n]
ericlewis.SpaceRace?[y/n]
ericlewis.SuperBreakout?[y/n]
ericlewis.QBert?[y/n]
Mazamars312.NeoGeo?[y/n]
nullobject.tecmo?[y/n]
boogermann.bankpanic?[y/n]
boogermann.digdug?[y/n]
boogermann.galaga?[y/n]
boogermann.gberet?[y/n]
boogermann.pooyan?[y/n]
boogermann.supervision?[y/n]
boogermann.xevious?[y/n]
Spacemen3.PDP1?[y/n]
Spiritualized.GB?[y/n]
Spiritualized.GBA?[y/n]
Spiritualized.GBC?[y/n]
Spiritualized.NES?[y/n]
Spiritualized.GG?[y/n]
Spiritualized.SMS?[y/n]
Spiritualized.SG-1000?[y/n]
Starting update process...
Checking for firmware updates...
Firmware update found. Downloading...
Download Complete
F:\pocket_firmware_B_7.bin
To install firmware, restart your Pocket.
-------------
Checking Core: agg23.Arduboy
0.9.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/agg23/openfpga-arduboy/releases/download/0.9.0/agg23.Arduboy.0.9.0.zip...
Extracting...
Installation complete.
-------------
Checking Core: agg23.Pong
1.2.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/agg23/openfpga-pong/releases/download/1.2.0/agg23.Pong_1.2.0_2022-09-08.zip...
Extracting...
Installation complete.
-------------
Checking Core: agg23.NES
0.2.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/agg23/openfpga-NES/releases/download/0.2.0/agg23.NES_0.2.0_2022-10-07.zip...
Extracting...
Installation complete.
-------------
Checking Core: agg23.SNES
0.3.2 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/agg23/openfpga-SNES/releases/download/0.3.2/agg23.SNES_0.3.2_2022-10-10.zip...
Extracting...
Installation complete.
-------------
Checking Core: ericlewis.Asteroids
1.0.1 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/ericlewis/openfpga-asteroids/releases/download/1.0.1/ericlewis.Asteroids_1.0.1_2022-10-11.zip...
Extracting...
Looking for Assets
Downloading asteroid.rom
Finished downloading asteroid.rom
Installation complete.
-------------
Checking Core: ericlewis.Dominos
0.0.1 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/ericlewis/openfpga-dominos/releases/download/0.0.1/ericlewis.Dominos_0.0.1_2022-09-17.zip...
Extracting...
Looking for Assets
Downloading dominos.rom
Finished downloading dominos.rom
Installation complete.
-------------
Checking Core: ericlewis.DonkeyKong
0.0.1 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/ericlewis/openFPGA-DonkeyKong/releases/download/0.0.1/ericlewis.DonkeyKong_0.0.1_2022-10-12.zip...
Extracting...
Looking for Assets
Downloading dkong.rom
Finished downloading dkong.rom
Installation complete.
-------------
Checking Core: ericlewis.Genesis
0.4.2 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/ericlewis/openFPGA-Genesis/releases/download/0.4.2/ericlewis.Genesis_0.4.2_2022-10-08.zip...
Extracting...
Installation complete.
-------------
Checking Core: ericlewis.LunarLander
0.9.1 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/ericlewis/openfpga-lunarlander/releases/download/0.9.1/ericlewis.LunarLander_0.9.1_2022-09-13.zip...
Extracting...
Looking for Assets
Downloading llander.rom
Finished downloading llander.rom
Installation complete.
-------------
Checking Core: ericlewis.SpaceRace
1.0.1 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/ericlewis/openfpga-spacerace/releases/download/1.0.1/ericlewis.SpaceRace_1.0.1_2022-10-11.zip...
Extracting...
Installation complete.
-------------
Checking Core: ericlewis.SuperBreakout
0.0.1 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/ericlewis/openfpga-superbreakout/releases/download/0.0.1/ericlewis.SuperBreakout_0.0.1_2022-09-14.zip...
Extracting...
Looking for Assets
Downloading sbrkout.rom
Finished downloading sbrkout.rom
Installation complete.
-------------
Checking Core: ericlewis.QBert
1.1.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/ericlewis/openfpga-qbert/releases/download/1.1.0/ericlewis.QBert_1.1.0_2022-10-17.zip...
Extracting...
Looking for Assets
Downloading qbert.rom
Finished downloading qbert.rom
Installation complete.
-------------
Checking Core: Mazamars312.NeoGeo
Alpha_0.7.5_2022-19-09 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/Mazamars312/Analogue_Pocket_Neogeo/releases/download/Alpha_0.7.5_2022-19-09/Mazamars312.Neogeo_Alpha_0.7.5_2022_19_09.zip...
Extracting...
Looking for Assets
Downloading zip file...
Extracting files...
Moving file: uni-bios_1_0.rom
Deleting temp files
Downloading 000-lo.lo
Finished downloading 000-lo.lo
Downloading sfix.sfix
Finished downloading sfix.sfix
Installation complete.
-------------
Checking Core: nullobject.tecmo
v2.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/nullobject/openfpga-tecmo/releases/download/v2.0/pocket-tecmo-2.0.zip...
Extracting...
Looking for Assets
Downloading gemini.rom
Finished downloading gemini.rom
Downloading rygar.rom
Finished downloading rygar.rom
Downloading geminij.rom
Finished downloading geminij.rom
Downloading rygar2.rom
Finished downloading rygar2.rom
Downloading rygarj.rom
Finished downloading rygarj.rom
Downloading silkworm.rom
Finished downloading silkworm.rom
Downloading silkwrmj.rom
Finished downloading silkwrmj.rom
Installation complete.
-------------
Checking Core: boogermann.bankpanic
0.1.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/opengateware/arcade-bankp/releases/download/0.1.0/boogermann.bankpanic_pocket-0.1.0.zip...
Extracting...
Downloading file https://github.com/opengateware/arcade-bankp/releases/download/0.1.0/boogermann.bankpanic_rom-recipes-0.1.0.zip...
Zip does not contain openFPGA core. Skipping. Please use -a if you'd like to extract all zips.
Looking for Assets
Downloading bankp.rom
Finished downloading bankp.rom
Downloading combh.rom
Finished downloading combh.rom
Installation complete.
-------------
Checking Core: boogermann.digdug
0.1.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/opengateware/arcade-digdug/releases/download/0.1.0/boogermann.digdug_pocket-0.1.0.zip...
Extracting...
Downloading file https://github.com/opengateware/arcade-digdug/releases/download/0.1.0/boogermann.digdug_rom-recipes-0.1.0.zip...
Zip does not contain openFPGA core. Skipping. Please use -a if you'd like to extract all zips.
Looking for Assets
Downloading digdug.rom
Finished downloading digdug.rom
Downloading digduat1.rom
Finished downloading digduat1.rom
Downloading digdug1.rom
Finished downloading digdug1.rom
Downloading digdugat.rom
Finished downloading digdugat.rom
Downloading digsid.rom
Finished downloading digsid.rom
Installation complete.
-------------
Checking Core: boogermann.galaga
v0.1.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/opengateware/arcade-galaga/releases/download/v0.1.0/arcade-galaga-pocket-v0.1.0.zip...
Extracting...
Downloading file https://github.com/opengateware/arcade-galaga/releases/download/v0.1.0/rom-recipes_0.1.0.zip...
Zip does not contain openFPGA core. Skipping. Please use -a if you'd like to extract all zips.
Looking for Assets
Downloading galaga.rom
Finished downloading galaga.rom
Downloading galagads.rom
Finished downloading galagads.rom
Downloading galagaef.rom
Finished downloading galagaef.rom
Downloading galagamf.rom
Finished downloading galagamf.rom
Downloading galagamw.rom
Finished downloading galagamw.rom
Downloading galagao.rom
Finished downloading galagao.rom
Downloading galagosb.rom
Finished downloading galagosb.rom
Downloading galagost.rom
Finished downloading galagost.rom
Downloading galaped.rom
Finished downloading galaped.rom
Downloading galgaxin.rom
Finished downloading galgaxin.rom
Downloading gatsbee.rom
Finished downloading gatsbee.rom
Downloading nebulbee.rom
Finished downloading nebulbee.rom
Downloading vgalaga.rom
Finished downloading vgalaga.rom
Downloading vgalagaf.rom
Finished downloading vgalagaf.rom
Downloading vgalagam.rom
Finished downloading vgalagam.rom
Installation complete.
-------------
Checking Core: boogermann.gberet
0.1.1 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/opengateware/arcade-gberet/releases/download/0.1.1/boogermann.gberet_pocket-0.1.1.zip...
Extracting...
Downloading file https://github.com/opengateware/arcade-gberet/releases/download/0.1.1/boogermann.gberet_rom-recipes-0.1.1.zip...
Zip does not contain openFPGA core. Skipping. Please use -a if you'd like to extract all zips.
Looking for Assets
Downloading gberet.rom
Finished downloading gberet.rom
Downloading mrgoemon.rom
Finished downloading mrgoemon.rom
Downloading rushatck.rom
Finished downloading rushatck.rom
Installation complete.
-------------
Checking Core: boogermann.pooyan
0.1.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/opengateware/arcade-pooyan/releases/download/0.1.0/boogermann.pooyan_pocket-0.1.0.zip...
Extracting...
Downloading file https://github.com/opengateware/arcade-pooyan/releases/download/0.1.0/boogermann.pooyan_rom-recipes-0.1.0.zip...
Zip does not contain openFPGA core. Skipping. Please use -a if you'd like to extract all zips.
Looking for Assets
Downloading pooyan.rom
Finished downloading pooyan.rom
Downloading pooyaiag.rom
Finished downloading pooyaiag.rom
Downloading pooyans.rom
Finished downloading pooyans.rom
Downloading pootan.rom
Finished downloading pootan.rom
Installation complete.
-------------
Checking Core: boogermann.supervision
0.1.1 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/opengateware/console-supervision/releases/download/0.1.1/boogermann.supervision_pocket-0.1.1.zip...
Extracting...
Installation complete.
-------------
Checking Core: boogermann.xevious
0.1.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/opengateware/arcade-xevious/releases/download/0.1.0/boogermann.xevious_pocket-0.1.0.zip...
Extracting...
Downloading file https://github.com/opengateware/arcade-xevious/releases/download/0.1.0/boogermann.xevious_rom-recipes-0.1.0.zip...
Zip does not contain openFPGA core. Skipping. Please use -a if you'd like to extract all zips.
Looking for Assets
Downloading battles2.rom
Finished downloading battles2.rom
Downloading gaous.rom
Finished downloading gaous.rom
Downloading sxevious.rom
Finished downloading sxevious.rom
Downloading xeviblk.rom
Finished downloading xeviblk.rom
Downloading xevios.rom
Finished downloading xevios.rom
Downloading xevious.rom
Finished downloading xevious.rom
Downloading xevious3.rom
Finished downloading xevious3.rom
Downloading xevious4.rom
Finished downloading xevious4.rom
Downloading xevious5.rom
Finished downloading xevious5.rom
Downloading xevioush.rom
Finished downloading xevioush.rom
Installation complete.
-------------
Checking Core: Spacemen3.PDP1
v1.1.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/spacemen3/PDP-1/releases/download/v1.1.0/Spacemen3.PDP1_1.1.0_2022-08-19.zip...
Extracting...
Installation complete.
-------------
Checking Core: Spiritualized.GB
v1.3.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/spiritualized1997/openFPGA-GB-GBC/releases/download/v1.3.0/Spiritualized_GBC_1.3.0_2022_08_25.zip...
Extracting...
Downloading file https://github.com/spiritualized1997/openFPGA-GB-GBC/releases/download/v1.3.0/Spiritualized_GB_1.3.0_2022_08_25.zip...
Extracting...
Installation complete.
-------------
Checking Core: Spiritualized.GBA
v1.2.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/spiritualized1997/openFPGA-GBA/releases/download/v1.2.0/Spiritualized_GBA_1.2.0_2022_08_25.zip...
Extracting...
Looking for Assets
Downloading gba_bios.bin
Finished downloading gba_bios.bin
Installation complete.
-------------
Checking Core: Spiritualized.GBC
v1.3.0 is the most recent release, checking local core...
local core found: v1.3.0
Looking for Assets
Downloading gbc_bios.bin
Finished downloading gbc_bios.bin
Downloading dmg_bios.bin
Finished downloading dmg_bios.bin
Up to date. Skipping core
-------------
Checking Core: Spiritualized.NES
1.0.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/spiritualized1997/openFPGA-NES/releases/download/1.0.0/Spiritualized_NES_1.0.0_2022_10_10.zip...
Extracting...
Looking for Assets
Downloading fds.bios
Finished downloading fds.bios
Installation complete.
-------------
Checking Core: Spiritualized.GG
v1.3.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/spiritualized1997/openFPGA-GG/releases/download/v1.3.0/Spiritualized_GG_1.3.0_2022_08_25.zip...
Extracting...
Installation complete.
-------------
Checking Core: Spiritualized.SMS
v1.2.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/spiritualized1997/openFPGA-SMS/releases/download/v1.2.0/Spiritualized_SMS_1.2.0_2022_08_25.zip...
Extracting...
Installation complete.
-------------
Checking Core: Spiritualized.SG-1000
v1.2.0 is the most recent release, checking local core...
Downloading core
Downloading file https://github.com/spiritualized1997/openFPGA-SG1000/releases/download/v1.2.0/Spiritualized_SG-1000_1.2.0_2022_08_25.zip...
Extracting...
Installation complete.
-------------
-------------
Update Process Complete
Cores Updated:
agg23.Arduboy 0.9.0
agg23.Pong 1.2.0
agg23.NES 0.2.0
agg23.SNES 0.3.2
ericlewis.Asteroids 1.0.1
ericlewis.Dominos 0.0.1
ericlewis.DonkeyKong 0.0.1
ericlewis.Genesis 0.4.2
ericlewis.LunarLander 0.9.1
ericlewis.SpaceRace 1.0.1
ericlewis.SuperBreakout 0.0.1
ericlewis.QBert 1.1.0
Mazamars312.NeoGeo 0.7.5
nullobject.tecmo 2.0.0
boogermann.bankpanic 0.1.0
boogermann.digdug 0.1.0
boogermann.galaga 0.1.0
boogermann.gberet 0.1.1
boogermann.pooyan 0.1.0
boogermann.supervision 0.1.1
boogermann.xevious 0.1.0
Spacemen3.PDP1 1.1.0
Spiritualized.GB 1.3.0
Spiritualized.GB 1.3.0
Spiritualized.GBA 1.2.0
Spiritualized.NES 1.0.0
Spiritualized.GG 1.3.0
Spiritualized.SMS 1.2.0
Spiritualized.SG-1000 1.2.0

Assets Installed:
F:\Assets/asteroids/ericlewis.Asteroids/asteroid.rom
F:\Assets/dominos/common/dominos.rom
F:\Assets/donkeykong/common/dkong.rom
F:\Assets/lunarlander/ericlewis.LunarLander/llander.rom
F:\Assets/superbreakout/common/sbrkout.rom
F:\Assets/qbert/common/qbert.rom
F:\Assets/ng/common\uni-bios_1_0.rom
F:\Assets/ng/common\000-lo.lo
F:\Assets/ng/common\sfix.sfix
F:\Assets/Tecmo/common\gemini.rom
F:\Assets/Tecmo/common\rygar.rom
F:\Assets/Tecmo/common\geminij.rom
F:\Assets/Tecmo/common\rygar2.rom
F:\Assets/Tecmo/common\rygarj.rom
F:\Assets/Tecmo/common\silkworm.rom
F:\Assets/Tecmo/common\silkwrmj.rom
F:\Assets/bankpanic/common/bankp.rom
F:\Assets/bankpanic/common/combh.rom
F:\Assets/DigDug/common/digdug.rom
F:\Assets/DigDug/common/digduat1.rom
F:\Assets/DigDug/common/digdug1.rom
F:\Assets/DigDug/common/digdugat.rom
F:\Assets/DigDug/common/digsid.rom
F:\Assets/Galaga/common/galaga.rom
F:\Assets/Galaga/common/galagads.rom
F:\Assets/Galaga/common/galagaef.rom
F:\Assets/Galaga/common/galagamf.rom
F:\Assets/Galaga/common/galagamw.rom
F:\Assets/Galaga/common/galagao.rom
F:\Assets/Galaga/common/galagosb.rom
F:\Assets/Galaga/common/galagost.rom
F:\Assets/Galaga/common/galaped.rom
F:\Assets/Galaga/common/galgaxin.rom
F:\Assets/Galaga/common/gatsbee.rom
F:\Assets/Galaga/common/nebulbee.rom
F:\Assets/Galaga/common/vgalaga.rom
F:\Assets/Galaga/common/vgalagaf.rom
F:\Assets/Galaga/common/vgalagam.rom
F:\Assets/gberet/common/gberet.rom
F:\Assets/gberet/common/mrgoemon.rom
F:\Assets/gberet/common/rushatck.rom
F:\Assets/pooyan/common/pooyan.rom
F:\Assets/pooyan/common/pooyaiag.rom
F:\Assets/pooyan/common/pooyans.rom
F:\Assets/pooyan/common/pootan.rom
F:\Assets/xevious/common/battles2.rom
F:\Assets/xevious/common/gaous.rom
F:\Assets/xevious/common/sxevious.rom
F:\Assets/xevious/common/xeviblk.rom
F:\Assets/xevious/common/xevios.rom
F:\Assets/xevious/common/xevious.rom
F:\Assets/xevious/common/xevious3.rom
F:\Assets/xevious/common/xevious4.rom
F:\Assets/xevious/common/xevious5.rom
F:\Assets/xevious/common/xevioush.rom
F:\Assets/gba/common/gba_bios.bin
F:\Assets/gbc/common/gbc_bios.bin
F:\Assets/gb/common/dmg_bios.bin
F:\Assets/nes/common/fds.bios

New Firmware was downloaded. Restart your Pocket to install
pocket_firmware_B_7.bin

we did it, come again soon

**Comment by mattpannella** [comment]
since running the updater on a local folder and moving the files to sd afterwards seems to solve this, i'm just gonna close the issue for now.
