### ISSUE TITLE
pulling files from

### ISSUE THREAD

**Issue by acidrain97** [mattpannella/pocket-updater-utility#57]
Can someone tell me where bios files ie intellivision is being pulled from? Can't seem to find it in the code.

thx

**Comment by mattpannella** [comment]
they get pulled from the archive.org archive in the settings file

**Comment by acidrain97** [comment]
Ok i'm very confused... are you talking about settings.cs? let me put it this way... Where are you getting intellivisions exec.intv and 12.bin from on archive.org? Can't find any of those files on archive.org. That's why I was  looking in the code trying to find where you were pulling from.

thx

**Comment by mattpannella** [comment]
nope, in your settings json file, sorry about that. its generated by the application and saved alongside it 
`pocket_updater_settings.json`

**Comment by acidrain97** [comment]
I give up... I still can not figure out where on archive.org you're pulling these files from... can you help me out a bit.... I'm not really great a C#...

**Comment by mattpannella** [comment]
sorry i was trying not to post the link on here. i'll delete this comment after you see it lol
from the settings file:
```
"archive_name": "openFPGA-Files",
```
