### ISSUE TITLE
Option If you wanna run core selector? 

### ISSUE THREAD

**Issue by Mika73** [mattpannella/pocket-updater-utility#58]
Would it be possible add option that pocket updater utility would ask if you wanna run core selector Y/N when you run it? 

Other question is that if run core pocket updater again with core selector option does it only remove core from list, it doesn’t delete any rom files from memory card?

**Comment by mattpannella** [comment]
you can run it any time by using -c on the command line or by setting `core_selector` to true in the settings file before running
and it doesn't delete anything in the assets directory, your roms will be safe. it just deletes the core

**Comment by mattpannella** [comment]
I misread lol yeah maybe prompting in the beginning is a good idea.

**Comment by Mika73** [comment]
Thank you :)

Does it ask if you wanna install if there becomes cores of new systems? Like new Arcade cores etc. If just run program or just update old ones you have select at first run? 

Lähetetty iPhonesta

**Comment by Mika73** [comment]
I did try run pocket updater with core selector true setting. I managed install few new cores and remove some unwanted but it won’t uninstall/remove Sorcer striker and Kindom
Granprix. I did just try those but now I can’t remove them anymore. 

Lähetetty iPhonesta

**Comment by mattpannella** [comment]
yeah its a known issue. the sorcer striker and kingdom cores are packaged in with battle garegga, instead of being their own releases. so they're not tracked by the updater properly. for now you'll have to just manually delete til i make a workaround

**Comment by Mika73** [comment]
How l remove those from menu? Is there easy way? 

Lähetetty iPhonesta

**Comment by mattpannella** [comment]
delete the folder for each one under Cores in your SD card

**Comment by mattpannella** [comment]
2.8.0 adds a menu that lets you run the core selector any time you want
