### ISSUE TITLE
Automatically installs newly released cores

### ISSUE THREAD

**Issue by LoneBoco** [mattpannella/pocket-updater-utility#59]
The utility automatically installs newly released cores.  For example, since the last time I ran the utility, the `boogermann.congo` core was released and the utility automatically downloaded and installed it.

It would be nice to be able to control how the utility handles new cores.  Either a setting to default allow/deny the new core, or maybe a setting to allow you to choose if it would be installed (like the core selector process, but only for the newly encountered cores).

**Comment by mattpannella** [comment]
i've gotta think about this for a bit, to decide how i wanna handle it
but yeah, you're probably right. the list is getting so massive, now, it would be nice to prompt for new ones. i just don't have anything in place to track whether anything is new or not, currently

**Comment by Tolaris** [comment]
> i've gotta think about this for a bit, to decide how i wanna handle it but yeah, you're probably right. the list is getting so massive, now, it would be nice to prompt for new ones. i just don't have anything in place to track whether anything is new or not, currently

I'm thinking on ways to track if something is new. In pocket_updater_settings.json, we have:

coreSettings": {
    "author.corename": {
      "skip": true|false,

For any new core, this setting won't be set at all. We could compare new cores to the coreSettings list to see if it's entirely unset, and then prompt the user what to do.

**Comment by LoneBoco** [comment]
> > i've gotta think about this for a bit, to decide how i wanna handle it but yeah, you're probably right. the list is getting so massive, now, it would be nice to prompt for new ones. i just don't have anything in place to track whether anything is new or not, currently
> 
> I'm thinking on ways to track if something is new. In pocket_updater_settings.json, we have:
> 
> coreSettings": { "author.corename": { "skip": true|false,
> 
> For any new core, this setting won't be set at all. We could compare new cores to the coreSettings list to see if it's entirely unset, and then prompt the user what to do.

That's what I figured.  I looked at the source code and it doesn't seem too difficult to implement.

I was thinking of a flow like this:

1. When the core selector process is ran, you first get a question that says, `Would you like to download all available cores?  [Y]es, [N]o, [A]sk for each.`
2. Save the result in the config settings.  `download_new_cores = yes|no|ask`
3. If [N] or [A] is chosen, run through the core selection for every available core.
4. When the core list is downloaded, check for an entry in `coreSettings`.  If an entry is not there, use the logic in the `download_new_cores` setting.  If set to `yes`, use existing logic and download.  If `no`, save the core entry to `coreSettings` and set `skip = true`.  If `ask`, then use the core selector prompt and follow the yes/no logic.

**Comment by mattpannella** [comment]
> > i've gotta think about this for a bit, to decide how i wanna handle it but yeah, you're probably right. the list is getting so massive, now, it would be nice to prompt for new ones. i just don't have anything in place to track whether anything is new or not, currently
> 
> I'm thinking on ways to track if something is new. In pocket_updater_settings.json, we have:
> 
> coreSettings": { "author.corename": { "skip": true|false,
> 
> For any new core, this setting won't be set at all. We could compare new cores to the coreSettings list to see if it's entirely unset, and then prompt the user what to do.

yup, correct
right now i just populate that list with a default for any core that comes down from the api that isn't already in the list, but i don't do anything with that and just blindly set them to true. 
so it wouldn't be a ton of work to change it to prompt with the new list at launch or something
i havent started on this yet, and might not for a few days, depending on how lazy i'm feeling lol. so if either of you want ot take a stab at it and make a PR feel free. if not i'll definitely get to it eventually
thanks!

**Comment by LoneBoco** [comment]
> > > i've gotta think about this for a bit, to decide how i wanna handle it but yeah, you're probably right. the list is getting so massive, now, it would be nice to prompt for new ones. i just don't have anything in place to track whether anything is new or not, currently
> > 
> > 
> > I'm thinking on ways to track if something is new. In pocket_updater_settings.json, we have:
> > coreSettings": { "author.corename": { "skip": true|false,
> > For any new core, this setting won't be set at all. We could compare new cores to the coreSettings list to see if it's entirely unset, and then prompt the user what to do.
> 
> yup, correct right now i just populate that list with a default for any core that comes down from the api that isn't already in the list, but i don't do anything with that and just blindly set them to true. so it wouldn't be a ton of work to change it to prompt with the new list at launch or something i havent started on this yet, and might not for a few days, depending on how lazy i'm feeling lol. so if either of you want ot take a stab at it and make a PR feel free. if not i'll definitely get to it eventually thanks!

I might make a go of it but first, what do you think of my proposed logic?  Should it be changed in any way?  My proposal would allow a method of downloading all cores at once and there have been people making these downloaders who didn't want that capability, so I just want to make sure what you are okay with before I do anything.

Just a recap but my proposal would change the initial core selection logic on first run to ask a question on if they want to auto download new cores.  The answer to that question will change how the software runs.  If yes, it will just download all cores and never prompt.  If no, it will go through the current core selection logic and never prompt on re-runs.  If ask, it will go through the current core selection logic and ask once on new cores.

**Comment by mattpannella** [comment]
hey sorry been super busy and havent come back to this haha
that sounds good to me
