### ISSUE TITLE
Install Image Pack #5 Froze microSD Card

### ISSUE THREAD

**Issue by dritzthevampyr** [mattpannella/pocket-updater-utility#64]
After choosing option 5 from the image packs, my entire microSD card (newest Samsung Pro Plus) randomly showed as empty and was stuck in a process even after I closed the terminal.  Then following a reboot of my MacBook, all folders are present again in the microSD (thank goodness).  As shown from the terminal output below - "something went wrong", but ended with 'Process Complete' even though the microSD seemed to still run the script (wouldn't eject without force quitting).  Not sure if this is the result of the image pack install itself or the updater utility.  

> Choose your destiny: 3
> 
> Checking for image packs...
> 
> 0) spiritualized1997: openFPGA-Platform-Art-Set 
> 1) dyreschlock: pocket-platform-images 
> 2) terminator2k2: Analogue-Pocket-Core-Art 
> 3) MegaZXretro: Analogue-Pocket-Custom-Platform-Art JAPAN
> 4) MegaZXretro: Analogue-Pocket-Custom-Platform-Art PAL-EU
> 5) MegaZXretro: Analogue-Pocket-Custom-Platform-Art USA
> 6) Go back
> 
> So, what'll it be?: 5
> Downloading image pack...
> Download complete.
> Installing...
> Well, something went wrong. Sorry about that.
> Input/output error : '/Volumes/Pocket/temp'
> 
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> Deleting expired sessions...none found.
> 
> [Process completed]

**Comment by mattpannella** [comment]
hm, I wonder if the SD card got unmounted or had a connection issue mid-process? I'm glad it turned out to be a false alarm

**Comment by dritzthevampyr** [comment]
Tested it out again, but this time the script worked.  Must've been a fluke occurrence.  Apologies!
