### ISSUE TITLE
Jotego jtbin core support

### ISSUE THREAD

**Issue by davewongillies** [mattpannella/pocket-updater-utility#66]
Add support for installing Jotego's cores from [jtbin](https://github.com/jotego/jtbin/tree/master/pocket)

**Comment by mattpannella** [comment]
they should all pull down now
its via a list i'm manually maintaining, like the pram0d cores, until the api officially supports them. but should be seamless on your end

**Comment by dji85** [comment]
@mattpannella from this list I'm not seeing a couple, including Outrun, unless they're not on the repo yet? Thanks!

https://github.com/jotego/jtframe/issues/78?fbclid=IwAR3p6lkxas_gMuE9f8w7j7VYsTXOqDB1nvTQFoClHGtieEUR_DZZGGKdIFg&mibextid=Zxz2cZ
