### ISSUE TITLE
How to Use This?

### ISSUE THREAD

**Issue by nealadam17** [mattpannella/pocket-updater-utility#68]
My apologies if I'm going about this the wrong way, this is my first time on GitHub. I was wondering if you could explain how to utilize this? I finally figured out that I can download a ZIP of the files by clicking on the green code button, I extracted the files and transferred them to my micro-SD card. The instructions I read online said that the included json file has every core inside of it, and that all you have to do is run 'pocket_updater'. How do I do that? Any file I click on, all I seem to be able to do is bring up the RAW on the internet. I'm very confused, any help would be greatly appreciated.

**Comment by mattpannella** [comment]
no worries, its not really very user friendly if you're not a developer. what you downloaded was just the source code
if you look on the right side of the main repository page (when you can see the readme) there is a section labeled Releases
thats where you can find the released versions of the app to download

**Comment by Tolaris** [comment]
Hopefully my latest pull request addresses this sufficiently and we can close this issue.
