### ISSUE TITLE
Check that ROM sources exist when referenced in JSON files

### ISSUE THREAD

**Issue by Tolaris** [mattpannella/pocket-updater-utility#75]
I used a crude method to verify that all ROMs existed on my filesystem:

grep '"filename":' Assets/*/*/*json Cores/*/data.json | grep -v NeoGeo | sed 's/^.*"filename": "//' | sed 's/".*$//' | sort -u > /tmp/needed
find  Assets/*/* -name \*rom | grep -v Assets/ng/common | sed 's@^.*/@@' | sort -u > /tmp/found

Then I used diff (Meld, in my case) to compare them and identify 4 missing ROMs.

A better method is to make a Python or similar script to traverse the JSON files and build a list of needed ROMs. Then check that each exists in the filesystem.

The best solution is to run this as a presubmit. Before merging in changes to pocket_updater_assets.json and pocket_updater_cores.json, check that all references in pocket_updater_cores.json have a matching reference in pocket_updater_assets.json. And also add a mode to pocket_updater to run in "testing mode", e.g. throw an exception when a rom 404's on download. If we run these two checks before checking in new changes, we'll ensure all new Cores+ROMs are correctly added.

I can write this in Python, but perhaps that's not the language you want for this project?

**Comment by mattpannella** [comment]
so, parsing the data.json and json files in the assets directory to pull all the required roms is actually gonna be in the api, soon. it's partially implemented already actually, the roms in data.json are returned, but I have a PR in to add support for the stuff in the assets directory. so i think some time kinda soon that'll be in, so we won't need to maintain the json file of assets anymore. 

adding a test mode to look for 404s is a really good idea, though

and you could still implement the verification of the assets json as a github action if you want but its not gonna be needed for long, so i wouldnt want you to waste a bunch of time on it

**Comment by mattpannella** [comment]
2.10.0 uses the local json files to build the list of required assets, now
