### ISSUE TITLE
Amiga core downloads lowercased "assets" and "platforms"

### ISSUE THREAD

**Issue by Tolaris** [mattpannella/pocket-updater-utility#84]
I updated the to 2.9.2 today and downloaded the amiga core. It installed the files in lowercase "assets" and "platforms" folders:

tyler@laptop:~/tmp/Pocket
$ find assets/amiga Assets/amiga/ platforms/_images/ 
assets/amiga
assets/amiga/common
assets/amiga/Mazamars312.amiga
assets/amiga/Mazamars312.amiga/mpu.bin
Assets/amiga/
Assets/amiga/common
Assets/amiga/common/kickstart.rom
platforms/_images/
platforms/_images/amiga.bin

The rest of my filesystem has "Assets" and "Platforms", and you can see that "common/kickstart.rom" is in the right folder but Mazamars312.amiga/mpu.bin is not.

Some guesses about what is happening:

I stage in a directory on an ext4 filesystem and then push to my exfat-formatted sdcards. ext4 is case-sensitive, exfat is case-preserving (aware of case but doesn't allow case collisions, like "assets" and "Assets" to co-exist). This means installing "assets/amiga" on an exfat filesystem that already has "Assets" will silently install into the "Assets" folder. So this bug will only present on a case-sensitive filesystem.

I looked through the pull requests for the Amiga core and can't see an obvious problem. Any ideas where this is caused?

**Comment by mattpannella** [comment]
yeah known issue, we have a request in to fix on the devs repo. it's how he packaged his release

**Comment by Tolaris** [comment]
Ok, thanks. Would you please link that request here and close this? Still finding how your tool pulls from other repos, but it's starting to make sense now.

**Comment by Tolaris** [comment]
Upstream issue.

**Comment by mattpannella** [comment]
https://github.com/Mazamars312/Analogue-Amiga/pull/7
https://github.com/Mazamars312/Analogue-Amiga/issues/11
