### ISSUE TITLE
Kaspersky antivirus

### ISSUE THREAD

**Issue by acidrain97** [mattpannella/pocket-updater-utility#85]
When executed "Access Denied" error then quarantines the file. VHO:Trojan-PSW.Win32.Convagent.gen. Zip file is being d/led from github. Anybody else getting the same thing?

**Comment by mattpannella** [comment]
not really sure what it could be detecting. but you can obviously look at the source here. and its being compiled by a github action, so its all done entirely on github

**Comment by acidrain97** [comment]
The updater from RetroDriven has issues with Win 11 Defender. I can't confirm it but if your program is setting off virus scanners then it could be a protentional problem. Otherwise it works fine. I use a Virtual Machine to run the program. FYI.
