### ISSUE TITLE
cores from pram0d's repo download every time

### ISSUE THREAD

**Issue by mattpannella** [mattpannella/pocket-updater-utility#87]
brainfart in the last release. the logic for checking versions won't work for the pram0d releases, so they will download every time

**Comment by Tolaris** [comment]
Same problem with Amiga?

Update Process Complete
Cores Updated:
Mazamars312.amiga 0.0.5

**Comment by Tolaris** [comment]
As of 2.9.4 Amiga downloads every time.

**Comment by mattpannella** [comment]
hm it shouldn't be. the issue was with the cores I'm manually adding support for until they're added to the inventory api officially.
I'll take a look in a bit and see if I can figure out what's up

**Comment by mattpannella** [comment]
i cant reproduce this. i guess make a new issue, so it doesnt get lost

**Comment by Tolaris** [comment]
I found the problem - it has to do with the Assets/assets lowercase issue. The problem doesn't happen when run from my exfat-formatted sdcard filesystem. It does happen when run from my ext4-formatted laptop root partition.

Probably just ignore this until upstream fixes the lowercase issue.

**Comment by mattpannella** [comment]
oh duh I should have suspected that haha
