### ISSUE TITLE
GBA Core Save Creation

### ISSUE THREAD

**Issue by LauraKBuzz** [mattpannella/pocket-updater-utility#90]
Hi.

I ran this utility today on a new out of box Analogue Pocket, and while the GBA Core does work, it books games correctly, it refuses to save. For some games I can make do with save states, but games like Minish Cap atlre unplayable, because they insist that my save data is corrupted, and won't let me create me create a save to start playing.

Looking on my SD card, there isn't a GBA folder in my saves folder. I tried creating a Saves / GBA / common folder to match the other systems, but  that didn't help.

Any ideas on what I need to do?

**Comment by mattpannella** [comment]
better off going to reddit or maybe making an issue on the repo for that core. i unfortunately dont have much insight into how the cores actually work. i do know saves aren't written til you close the core, maybe its related to that?
https://github.com/spiritualized1997/openFPGA-GBA
