### ISSUE TITLE
When taking automated arguments, don't require user interaction

### ISSUE THREAD

**Issue by Tolaris** [mattpannella/pocket-updater-utility#91]
`pocket_updater -u` should not require the user to press Enter to exit.

Since we're bypassing the prompts and updating, when we reach the end, do not pause and require the user to press Enter after printing "we did it, come again soon". Just exit.

**Comment by mattpannella** [comment]
I put the pause in at the end because on windows if you just launch the application from explorer it instantly closes the window when it's finished, so you can't see the log. there's probably a better way to do it but it's just been that way and I never revisited it haha

**Comment by mattpannella** [comment]
(will fix in next release)

**Comment by Tolaris** [comment]
On windows, when you define the shortcut, there's an option to keep the terminal open after the command exits. I forget exactly what it's called. But perhaps we can set that in the installer?

**Comment by Tolaris** [comment]
If the program needs to behave in a way Windows users expect, that's fine. Currently it behaves very little like a typical Linux CLI tool. And we can expect most users to run Windows or Mac.

But I'd love if there was a switch like --terminal_mode or a single-letter flag which enabled "non-interactive mode". E.g. let me pass my intent via CLI flags.

**Comment by mattpannella** [comment]
it doesnt necessarily need to behave any single way, just more the reality is i never test it as a cli app lol cuz i started working on this assuming most people have no idea what that means and just wanna double click a file and have it "do the thing"
i definitely can and should put a bit more time into testing it as an actual cli app to ensure it behaves the way people expect

**Comment by Tolaris** [comment]
If I had a Windows build environment I could help with that, but I'm afraid that's off the cards for me. Thanks for looking at it! Happy to test builds.

**Comment by mattpannella** [comment]
I haven't really had much time to work on this yet but the latest release does exit without waiting for input now

**Comment by mattpannella** [comment]
put a little more time into this
https://github.com/mattpannella/pocket-updater-utility/releases/tag/2.29.0

**Comment by mattpannella** [comment]
@Tolaris i spent some time tonight really re-factoring how the cli params work. i think this may be much more inline with what you're looking for
check out version 2.33.0

**Comment by Tolaris** [comment]
Thanks, I've tested and this is an improvement! Thank you! Consider this bug closed unless ...

I have some suggestions for minor improvements! Would you like these filed as additional issues?

1. When running --help, don't check for updates. --help should be fast and exit immediately.

2. Help usually has a sample invocation. This syntax indicates a single optional action and multiple optional arguments. I suggest adding to the help like so:

```
usage: pocket_updater [ACTION] [OPTION] [...]
  menu                 (Default action) Interactive Main Menu
```

3. As above, change "default verb" to "default action". I file "verb" to be creative :) but I've never seen that term used to mean this in other CLIs.

4. Add an action to update self and exit silently (no user interaction):
```  update_self          Update only the Pocket Updater Utility and exit```
  
5. Add an argument to skip the update self step wherever it is automatic:
```  --skip_update_self```

Here's why I like #4 and #5. I'll use a simple script to update pocket-updater, let it exit, and then run the new version to update all. Since you had trouble making that work in a cross-platform way (that's not surprising, it's complex), this allows me to write a wrapper that runs on linux and does the same. You are welcome to it if you want it, but it's just a bash script.

**Comment by Tolaris** [comment]
OK, let's ignore suggestion 3. I didn't realise this was an implentation detail of CommandLineParser. That's weird, but no reason to make it your problem. https://github.com/commandlineparser/commandline/wiki/Verbs#default-verb

;)

**Comment by Tolaris** [comment]
Suggestion 2 can be done fairly easily:

https://github.com/commandlineparser/commandline/wiki/HelpText-Configuration#helptext-setting

AddPreOptionsLine(String)	Adds a text line after copyright and before options usage strings.

**Comment by mattpannella** [comment]
yeah moving the update check was gonna be next on my list haha. I need to refactor a bunch of this cuz it's a bit of a mess, so for round 1 I just mostly left it alone and just adjusted the parameters. all good suggestions. we can just leave them in this thread I guess

**Comment by mattpannella** [comment]
https://github.com/mattpannella/pocket-updater-utility/releases/tag/2.35.0

i disabled the update check unless running the app via the menu
added a new command for updating. `update-self`

**Comment by Tolaris** [comment]
Tested 2.35.0 and this works great for non-interactive scripting, thank you! My script:

```
#!/bin/bash
MAIN_DIR="$HOME/Private/Games/Pocket"
COMMAND="./pocket_updater_x64"
cd $MAIN_DIR
$COMMAND update-self
if [ -f "pocket_updater.zip" ] ; then
  unzip -o pocket_updater.zip
  mv pocket_updater.zip pocket_updater_old.zip
  $COMMAND update
fi
```

This runs the self-updater and lets it exit. Then if it finds a new zip file, it unzips it and runs the update command.
